version: "3.3"
services:
  app:
    build: .
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid; bundle exec rails s"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    depends_on:
      - mysql
    tty: true
    stdin_open: true

  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306
    volumes:
      - ./docker/mysql/volumes/data:/var/lib/mysql

