version: '3.4'
services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    tty: true
    stdin_open: true

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: bash -c "redis-server --appendonly yes"

