version: "3.3"
services:
  app:
    build: .
    env_file:
      app.env
    environment:
      RAILS_ENV: development
    depends_on:
      - mysql
    volumes:
      - .:/app
    ports:
      - 3000:3000
    networks:
      - default
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid; bundle exec rails s"

  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default
    ports:
      - 3306:3306
    command: mysqld
    volumes:
      - ./docker/mysql/volumes:/var/lib/mysql
